

export const replacements_s = {
  ArdenBlue: "ArdenBlue_GrainyNatural",
  BlancoMaple14: "BlancoMaple14_Tropical-Forest",
  OceanStorm: "OceanStorm_Superstellar",
  SiennaRidge12: "SiennaRidge12_NewMountain",
  Yukon: "Yukon_Rivers",
  CopperMist: "CopperMist_Influencer",
  Lusso: "Lusso_Influencer",
  BlancoCity: "BlancoCity_Project-Basiq",
  CoralClayColour: "CoralClayColour_Project-Basiq",
  Marengo: "Marengo_Project-Basiq",
  Rougui: "Rougui_Project-Basiq",
  WhiteStorm14: "WhiteStorm14_Project-Basiq",
  BlancoNorte14: "BlancoNorte14_Mythology",
  BlancoZeus: "BlancoZeus_Mythology",
  GrisExpo: "GrisExpo_Mythology",
  MiamiWhite17: "MiamiWhite17_Mythology",
  NightTebas18: "NightTebas18_Mythology",
  Helix: "Helix_NebulaCode",
  Halcyon: "Halcyon_Nebula",
  Lagoon: "Lagoon_Nebula",
  Lyra: "Lyra_Nebula",
  MiamiVena: "MiamiVena_Nebula",
  LinenCream: "LinenCream_Suma",
  MotionGrey: "MotionGrey_Suma",
  PersianWhite: "PersianWhite_Suma",
  SiberianFrost: "SiberianFrost_Suma",
  StellarBlanco13: "StellarBlanco13_Stellar",
  StellarNight: "StellarNight_Stellar",
  EclecticPearl: "EclecticPearl_LeChic",
  RomanticAsh: "RomanticAsh_LeChic",
  VersaillesIvory: "VersaillesIvory_LeChic",
  VictorianSilver: "VictorianSilver_LeChic",
  BrassRelish: "BrassRelish_UrbanCrush",
  CinderCraze: "CinderCraze_UrbanCrush",
  ConcretePulse: "ConcretePulse_UrbanCrush",
  LimeDelight: "LimeDelight_UrbanCrush",
  EtherealCloud: "EtherealCloud_Ethereal",
  EtherealDusk: "EtherealDusk_Ethereal",
  EtherealGlow: "EtherealGlow_Ethereal",
  EtherealHaze: "EtherealHaze_Ethereal",
  EtherealIndigo: "EtherealIndigo_Ethereal",
  EtherealNoctis: "EtherealNoctis_Ethereal",
  PearlJasmine: "PearlJasmine_Eternal",
  ToscanaCream: "ToscanaCream_Eternal",
  CharcoalSoapstone: "CharcoalSoapstone_Eternal",
  ClassicCalacatta: "ClassicCalacatta_Eternal",
  DesertSilver: "DesertSilver_Eternal",
  WhiteArabesque: "WhiteArabesque_NebulaAlpha",
  SnowyIbiza: "SnowyIbiza_NebulaAlpha",
  Calypso: "Calypso_NebulaAlpha",
  BlancoOrion: "BlancoOrion_NebulaAlpha",
  Ariel: "Ariel_NebulaAlpha",
  EtBella: "EtBella_Eternal",
  EtCalacattaGold: "EtCalacattaGold_Eternal",
  EtDOr: "EtDOr_Eternal",
  EtMarfil: "EtMarfil_Eternal",
  EtNoir: "EtNoir_Eternal",
  EtStatuario: "EtStatuario_Eternal",
  EtMarquina: "EtMarquina_Eternal"
};

  
export const getReplacements_S = () => replacements_s;
  